# How to create Rank 1 numpy arrays:

In [3]:
import numpy as np
an_array = np.array([3, 33, 333]) # Create a rank 1 array
print(type(an_array))             # The type of an ndarray is: "<class 'numpy.ndarray'>"

<class 'numpy.ndarray'>


In [5]:
# test the shape of the array we just created, it should have just one dimension
print(an_array.shape)

(3,)


In [6]:
# because this is a 1-rank array, we need only one index to access each element
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [7]:
an_array[0] = 888                 #n darrays are mutable, here we change an element of the array
print(an_array)

[888  33 333]


In [9]:
another = np.array([[11, 12, 13], [21, 22, 23]]) # Create a rank 2 array

print(another) # Print the array

print("The shape is 2 rows, 3 columns: ", another.shape) # rows x columns

print("Accessing elements [0,0][0,1], and [1,0] of the ndarray: ", another[0,0], ", ", another[0,1], ", ", another[1,0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns:  (2, 3)
Accessing elements [0,0][0,1], and [1,0] of the ndarray:  11 ,  12 ,  21


In [10]:
import numpy as np

# Create a 2x2 array of zeros
ex1 = np.zeros((2,2))
print(ex1)

[[ 0.  0.]
 [ 0.  0.]]


In [17]:
# Create a 2x2 array filled with 9.0
ex2 = np.full((2, 2), 9.1)
print(ex2)

[[ 9.1  9.1]
 [ 9.1  9.1]]


In [23]:
# Create a 2x2 matrix with the diagonal 1s and the others 0
ex3 = np.eye(10,10)
print(ex3)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [21]:
# Create an array of ones
ex4 = np.ones((3,2))
print(ex4)

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


In [24]:
# Create an array of random floats between 0 and 1
ex5 = np.random.random((2,2))
print(ex5)

[[ 0.24900264  0.76683811]
 [ 0.27983592  0.47846464]]


# Array Indexing

In [34]:
import numpy as np

# Rank 2 array of shape (3, 4)
an_array = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [35]:
a_slice = np.array(an_array[:2, 1:3])
print(a_slice)

[[12 13]
 [22 23]]


In [36]:
print("Before: ", an_array[0,1]) # inspect the element at 0, 1
a_slice[0,0] = 1000 # a_slice[0,0] is the same piece of data as an_array[0,1]
print("After: ", an_array[0,1])

Before:  12
After:  12


# Use both integer indexing & slice indexing

In [37]:
# Create a Rank 2 array of shape(3,4)
an_array = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])

print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [38]:
# Using both integer indexing & slicing generates an array of lower rank
row_rank1 = an_array[1, :] # Rank 1 view

print(row_rank1, row_rank1.shape) # Notice only a single

[21 22 23 24] (4,)


In [41]:
# Slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2, :] # Rank 2 view

print(row_rank2, row_rank2.shape) # Notice the [[ ]]

[[21 22 23 24]] (1, 4)


In [51]:
# We can do the same thing for columns of an array:

print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape) # Rank 1
print()
print(col_rank2, col_rank2.shape) # Rank 2


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


# Array Indexing for changing elements:

In [52]:
# Create a new array
an_array = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33], [41, 42, 43]])

print("Original Array: ")
print(an_array)

Original Array: 
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [56]:
# Create an array of indices
col_indices = np.array([0, 1, 2, 0])
print("\nCol indices picked : ", col_indices)

row_indices = np.arange(4)
print("\nRows indices picke : ", row_indices)


Col indices picked :  [0 1 2 0]

Rows indices picke :  [0 1 2 3]


In [57]:
# Examine the pairing of row_indices and col_indices. These are the elementes we'll change next.
for row, col in zip(row_indices,col_indices):
    print(row, ", ", col)

0 ,  0
1 ,  1
2 ,  2
3 ,  0


In [58]:
# Select one element from each row
print("Values in the array at those indices: ", an_array[row_indices, col_indices])

Values in the array at those indices:  [11 22 33 41]


In [59]:
# Change one element from each row
print('Values in the array at those indices: ', an_array[row_indices, col_indices])

Values in the array at those indices:  [11 22 33 41]


In [60]:
# Change one element from each row using the indices selected
an_array[row_indices, col_indices] += 100000

print("\nChanged Array: ")
print(an_array)


Changed Array: 
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


In [66]:
# Question:
arr = np.zeros((3,3))
print(arr[:2,])

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


# Boolean Indexing

In [83]:
# Create a 3x2 array
an_array = np.array([[11, 12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [84]:
# Create a filter wich will be boolean values for whether each element meets this condition
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]], dtype=bool)

In [85]:
# We can now select just those elements wich meet that criteria
print(an_array[filter])

[21 22 31 32]


In [86]:
# For short, we could have just used the approach below without the need for the separate filter array.
print(an_array[an_array > 15])

# > 20 & < 30
print(an_array[(an_array > 20) & (an_array < 30)])

# % 2 == 0
print(an_array[(an_array % 2 == 0)])

[21 22 31 32]
[21 22]
[12 22 32]


In [87]:
an_array[an_array % 2 == 0] += 100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


# Datatypes and Array Operations

In [88]:
ex1 = np.array([11, 12]) # Python assigns the data type
print(ex1.dtype)

int64


In [89]:
ex2 = np.array([11.0, 12.0]) # Python assigns the data type
print(ex2.dtype)

float64


In [91]:
ex3 = np.array([11, 21], dtype=np.int64) # You can also tell Python the data type
print(ex3.dtype)

float64


In [98]:
# You can use this to force floats into integers (using floor function)
ex4 = np.array([11.1, 12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [99]:
# You can use this to force integers into floats if you antecipate
# the values may change the floats later
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[ 11.  21.]


# Arithmetic Array Operations: 

In [100]:
x = np.array([[111, 112], [121, 122]], dtype=np.int)
y = np.array([[211.1, 212.1], [221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[ 211.1  212.1]
 [ 221.1  222.1]]


In [101]:
# Add
print(x + y)
print()
print(np.add(x, y))

[[ 322.1  324.1]
 [ 342.1  344.1]]

[[ 322.1  324.1]
 [ 342.1  344.1]]


In [102]:
# Subtract
print( x - y )
print()
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [104]:
# Multiply
print( x * y )
print()
print(np.multiply(x, y))

[[ 23432.1  23755.2]
 [ 26753.1  27096.2]]

[[ 23432.1  23755.2]
 [ 26753.1  27096.2]]


In [105]:
# Divide
print( x / y )
print()
print(np.divide(x, y))

[[ 0.52581715  0.52805281]
 [ 0.54726368  0.54930212]]

[[ 0.52581715  0.52805281]
 [ 0.54726368  0.54930212]]


In [106]:
# Square Root
print(np.sqrt(x))

[[ 10.53565375  10.58300524]
 [ 11.          11.04536102]]


In [107]:
# Exponent ( e ** x)
print(np.exp(x))

[[  1.60948707e+48   4.37503945e+48]
 [  3.54513118e+52   9.63666567e+52]]


# Statistical Methods, Sorting, and Set Operations:

<p style="font-family: Arial; font-size:1.75em; color:#2462C0; font-style:bold">
<br>
Basic Statistical Operations:

In [109]:
# Setup a random 2 x 4 matrix
arr = 10 * np.random.randn(2,5)
print(arr)

[[ 10.23189654  12.1804774   -9.59324837   3.00135333   1.09661443]
 [ -5.97487422   8.94375905  13.54270564  23.43436907   0.87647206]]


In [110]:
# Compute the mean for all elements
print(arr.mean())

5.77395249256


In [111]:
# Compute the means by row
print(arr.mean(axis = 1 ))

[ 3.38341866  8.16448632]


In [112]:
# Compute the means by column
print(arr.mean(axis = 0))

[  2.12851116  10.56211822   1.97472863  13.2178612    0.98654325]


In [113]:
# Sum all the elements
print(arr.sum())

57.7395249256


In [114]:
# Compute the medians
print(np.median(arr, axis = 1))

[ 3.00135333  8.94375905]


# Sorting:

In [119]:
# Create a 10 element array of randoms
unsorted = np.random.randn(10)

print(unsorted)

[-0.43895429 -2.38381342 -1.53390236 -0.79174086 -1.61327745  0.70422417
 -0.11869554 -1.46106595  1.16193522 -0.55825082]


In [122]:
# Create copy and sort
sorted = np.array(unsorted)
sorted.sort()

print(sorted)
print()
print(unsorted)

[-2.38381342 -1.61327745 -1.53390236 -1.46106595 -0.79174086 -0.55825082
 -0.43895429 -0.11869554  0.70422417  1.16193522]

[-2.38381342 -1.61327745 -1.53390236 -1.46106595 -0.79174086 -0.55825082
 -0.43895429 -0.11869554  0.70422417  1.16193522]


In [123]:
# Inplace sorting
unsorted.sort()

print(unsorted)

[-2.38381342 -1.61327745 -1.53390236 -1.46106595 -0.79174086 -0.55825082
 -0.43895429 -0.11869554  0.70422417  1.16193522]


# Finding Unique elements:

In [124]:
array = np.array([1, 2, 1, 4, 2, 1, 4, 2])
print(np.unique(array))

[1 2 4]


# Set Operations with np.array data type:

In [136]:
s1 = np.array(['desk', 'chair', 'bulb'])
s2 = np.array(['lamp', 'bulb', 'chair'])

print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [126]:
print(np.intersect1d(s1, s2))

['bulb' 'chair']


In [127]:
print(np.union1d(s1, s2))

['bulb' 'chair' 'desk' 'lamp']


In [129]:
print(np.setdiff1d(s1, s2)) # Element in s1 that are not in s2

['desk']


In [135]:
print(np.in1d(s1, s2)) # Which element of s1 is also in s2

[False  True  True]


# Broadcasting:

In [137]:
import numpy as np

start = np.zeros((4,3))
print(start)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [138]:
# Create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [139]:
y = start + add_rows # Add to each row of 'start' using broadcasting
print(y)

[[ 1.  0.  2.]
 [ 1.  0.  2.]
 [ 1.  0.  2.]
 [ 1.  0.  2.]]


In [140]:
# Create an ndarray which is 4 x 1 to broadcast across columns 
add_cols = np.array([[0, 1, 2, 3]])
add_cols = add_cols.T

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [141]:
# Add to each column of 'start' using broadcasting
y = start + add_cols
print(y)

[[ 0.  0.  0.]
 [ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]]


In [142]:
# This will just broadcast in both dimensions
add_scalar = np.array([1])
print(start+add_scalar)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [143]:
# Create our 3x4 matrix
arrA = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [144]:
# Create our 4x1 matrix
a = np.array([[0,0],[0,0]])
b1 = np.array([1,1])
b2 = 1
print(a+b1)
print(a+b2)

[[1 1]
 [1 1]]
[[1 1]
 [1 1]]


# Speedtest: ndarrays vs lists:

In [145]:
from numpy import arange
from timeit import Timer

size = 1000000
timeits = 1000

In [146]:
# Create the ndarray with values 0, 1, 2 ..., size-1
nd_array = arange(size)
print(type(nd_array))

<class 'numpy.ndarray'>


In [147]:
# Timer expects the operation as a parameter,
# Here we pass nd_array.sum()
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" % (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.000762 seconds


In [148]:
# Create the list with values 0, 1, 2 ..., size-1
a_list = list(range(size))
print(type(a_list))

<class 'list'>


In [149]:
# Timer expects the operation as a parameter,
# Here we pass sum(a_list)
timer_list = Timer("sum(a_list)", "from __main__ import a_list")
print("Time taken by numpy ndarray: %f seconds" % (timer_list.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.009179 seconds


# Read or Write to Disk: